name: SAST Scan

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-python@v5

        with:
          python-version: 3.x

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
